spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/taskapp_db
spring.datasource.username=root
spring.datasource.password=angeltrajkov2003
spring.security.user.name=myusername
spring.security.user.password=mypassword123
spring.jpa.hibernate.ddl-auto=update
spring.web.error.include-message=always
spring.jpa.show-sql=true
